th main.lua \
-epochSize 80000 \
-batchSize 1 \
-imageSize 565 \
-imageCrop 565 \
-iterSize 1 \
-nGPU 1 \
-nDonkeys 3 \
-nEpochs 20 \
-netType milvc_stackvcnn \
-dataset mscoco \
-data data/MSCOCO \
-train -test
